# Generated by Django 5.0.6 on 2024-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_remove_booking_seat_booking_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
