# Generated by Django 5.0.6 on 2024-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_alter_booking_seat_number_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
