# Generated by Django 5.0.6 on 2024-06-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_booking_is_cancelled_train_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_category',
            field=models.CharField(choices=[('Second Class', 'Second Class'), ('First Class', 'First Class'), ('AC', 'AC')], default='Second Class', max_length=20),
        ),
    ]
