# Generated by Django 5.0.6 on 2024-06-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_booking_seat_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_category',
        ),
    ]
