# Generated by Django 5.0.6 on 2024-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_remove_booking_seat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='first_class_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='first_tier_price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='second_class_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8),
        ),
        migrations.AddField(
            model_name='train',
            name='sleeper_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
