# Generated by Django 5.0.6 on 2024-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_train_first_class_price_train_first_tier_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='On Time', max_length=20),
        ),
    ]
